config/routes.rb
require 'sidekiq/web'

Certificados::Application.routes.draw do

  resources :validations, :only => [:new, :create, :show]

  resources :certificates, :only => [] do
    get :autocomplete_certificate_uuid, :on => :collection
  end

  get "students/imports/new" => "students#new_import", :as => :new_students_import
  post "students/imports" => "students#create_import", :as => :students_import
  get "lecturers/imports/new" => "lecturers#new_import", :as => :new_lecturers_import
  post "lecturers/imports" => "lecturers#create_import", :as => :lecturers_import
  post "certificates/:certificate_id/mail/" => "certificate_mail#create", :as => :email_certificate
  get "certificates/search/" => "certificates#search", :as => :search_certificates
  get "certificates/" => "certificates#index", :as => :certificates
  get "certificates/filter" => "certificates#filter", :as => :filter_certificates


  [:lecturers, :students].each do |r|
    resources r do
      resources :certificates, :except => [:edit, :update, :index], :shallow => true do
        resources :send_attempts, :only => [:index], :shallow => true
      end
    end
  end

  resource :validation, :only => [:new, :create], :shallow => true

  mount Sidekiq::Web, at: "/sidekiq"
  root :to => "certificates#index"
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :certificates, :as => :certifiable, :dependent => :destroy

  attr_accessible :name, :cpf, :rg, :email, :phone1, :phone2, :phone3, :address,
                    :zip, :neighborhood, :city, :sex, :birth_date, :occupation,
                    :address_complement

end

app/controllers/students_controller.rb
# encoding: utf-8

class StudentsController < ApplicationController
  def new_import
  end

  def create_import
    students = params[:certifiable_attributes]
    students.each do |student|
      certificate = student[:certificate_attributes]
      certificate['kind'] = "course"
      student.delete :certificate_attributes
      s = Student.create(student)
      s.certificates.create(certificate)
    end
    redirect_to students_path
  end

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(params[:student])
    if @student.save
      redirect_to @student, notice: 'Student was successfully created.'
    else
      render :new
    end
  end

  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(params[:student])
      redirect_to @student, notice: 'Student was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_url
  end
end

app/views/students/_form.html.erb
<%= form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br />
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone1 %><br />
    <%= f.text_field :phone1 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form', :student => @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>
<%= link_to 'New Student', new_student_path %>

<table>
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Cpf</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.id %></td>
    <td><%= student.name %></td>
    <td><%= student.cpf %></td>
    <td><%= student.email %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form', :student => @student %>

<%= link_to 'Back', students_path %>

app/views/students/new_import.html.erb
<h2>Cole aqui os dados do Excel</h1>
<div id="dataTable" class="dataTable"
data-attributes="name,email,phone1,course,course_code,duration,start_date,end_date,topics"
data-end="2"></div>

<button class="submit">Enviar</button>
<br /><br />
<%= link_to 'Voltar', students_path %>
<form action="<%= students_import_path %>" id="import_data" method="POST">
</form>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Cpf:</b>
  <%= @student.cpf %>
</p>

<p>
  <b>Email:</b>
  <%= @student.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @student.phone1 %>
</p>



<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %> |
<%= link_to 'New Certificate', new_student_certificate_path(@student) %>

<h2>Certificados</h2>

<% if @student.certificates.empty? %>
    <p>Não existem certificados gerados para este aluno.</p>
<% else %>
<table>
  <tr>
    <th>Titulo</th>
    <th>Geração</th>
    <th>Enviado?</th>
    <th>Tentativas</th>
    <th>uuid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @student.certificates.each do |certificate| %>
  <tr>
    <td><%= certificate.title %></td>
    <td><%= certificate.created_at.strftime("%d-%m-%Y %H:%M") %></td>
    <td><%= certificate.sent %></td>
    <td><%= link_to certificate.attempts, certificate_send_attempts_path(certificate) %></td>
    <td><%= certificate.uuid %></td>
    <td><%= link_to 'Show', certificate %></td>
    <td><%= link_to 'Destroy', certificate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Enviar', email_certificate_path(certificate), method: :post%></td>
  </tr>
<% end %>
</table>
<% end %>