config/routes.rb
require 'sidekiq/web'

Certificados::Application.routes.draw do

  resources :validations, :only => [:new, :create, :show]

  resources :certificates, :only => [] do
    get :autocomplete_certificate_uuid, :on => :collection
  end

  get "students/imports/new" => "students#new_import", :as => :new_students_import
  post "students/imports" => "students#create_import", :as => :students_import
  get "lecturers/imports/new" => "lecturers#new_import", :as => :new_lecturers_import
  post "lecturers/imports" => "lecturers#create_import", :as => :lecturers_import
  post "certificates/:certificate_id/mail/" => "certificate_mail#create", :as => :email_certificate
  get "certificates/search/" => "certificates#search", :as => :search_certificates
  get "certificates/" => "certificates#index", :as => :certificates
  get "certificates/filter" => "certificates#filter", :as => :filter_certificates


  [:lecturers, :students].each do |r|
    resources r do
      resources :certificates, :except => [:edit, :update, :index], :shallow => true do
        resources :send_attempts, :only => [:index], :shallow => true
      end
    end
  end

  resource :validation, :only => [:new, :create], :shallow => true

  mount Sidekiq::Web, at: "/sidekiq"
  root :to => "certificates#index"
end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  before_create :fill_defaults

  belongs_to :certifiable, :polymorphic => true
  has_many :send_attempts, :dependent => :destroy

  attr_accessible :event, :lecture, :course, :course_code, :duration,
                  :start_date, :end_date, :topics, :kind

  validates :course_code, :duration, :certifiable_id, :presence => true
  validates :start_date, :end_date, :course, :presence => true, :if => :course?
  validates :event, :presence => true, :if => :event?
  validates :lecture, :presence => true, :if => :event_and_lecturer?
  delegate :name, :to => :certifiable, :prefix => true

  def attempts()
    self.send_attempts.count
  end

  def pdf_file()
    require 'pdfkit'
    certificate_url = Rails.application.routes.url_helpers.certificate_url(self,
        :host => "0.0.0.0", :port => "3000")
    kit = PDFKit.new(certificate_url, :orientation => 'Landscape',
        :margin_left => 2,
        :margin_right => 2,
        :margin_bottom => 2,
        :margin_top => 2,
        :encoding => 'UTF-8')
    kit.to_pdf
  end

  def title
    self.send self.kind
  end

  def send_email
    EmailWorker.perform_async(self.id)
  end

  protected
  def event?
    self.kind == "event"
  end

  def event_and_lecturer?
    self.kind == "event" and self.certifiable_type == "Lecturer"
  end

  def course?
    self.kind == "course"
  end

  def fill_defaults
    self.uuid = UUID.new.generate
    self.sent = false
    true
  end
end

app/controllers/certificates_controller.rb
# encoding: utf-8

class CertificatesController < ApplicationController
  autocomplete :certificate, :uuid, :full => false
  layout "certificate", :only => [:show]

  def index
  end

  def show
    @certificate = Certificate.find(params[:id])
    @certifiable = @certificate.certifiable
  end

  def new
    if params.has_key? :student_id
      @certifiable = Student.find(params[:student_id])
    else
      @certifiable = Lecturer.find(params[:lecturer_id])
    end
    @certificate = Certificate.new
  end

  def create
    if params.has_key? :student_id
      @certifiable = Student.find(params[:student_id])
    else
      @certifiable = Lecturer.find(params[:lecturer_id])
    end
    @certificate = Certificate.new(params[:certificate])
    @certificate.certifiable = @certifiable
    if @certificate.save
      redirect_to @certificate, notice: 'Certificate was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @certificate = Certificate.find(params[:id])
    certifiable = @certificate.certifiable
    @certificate.destroy
    redirect_to certifiable
  end

  def search
    certificate = Certificate.find_by_uuid!(params[:certificate][:search])
    redirect_to certificate
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "Não há certificado identificado por #{params[:certificate][:search]}."
    render :index
  end

  def filter
    @certificates = Certificate.find_all_by_course_code(params[:certificate][:filter])
    render :index
  end
end

app/helpers/certificates_helper.rb
module CertificatesHelper
    def slice_topics(topics)
        topics = topics.split(",")
        size = (topics.length/2.0).ceil()
        return topics.each_slice(size)
    end
end

app/views/certificates/_course.html.erb
A IT Cursos certifica a participação de <strong><%= certifiable.name.upcase %></strong> no curso <strong><%= certificate.course.upcase %></strong>, com carga horária total de <strong><%= certificate.duration %></strong>,  realizado no período de <strong><%= certificate.start_date %></strong><% unless certificate.start_date == certificate.end_date %> a <strong><%= certificate.end_date %></strong><% end %>, em Natal/RN<% if certificate.certifiable_type == "Lecturer" %>, na qualidade de <strong>PROFESSOR</strong><% end %>.

<div id="topics">
<h2>CONTEÚDO PROGRAMÁTICO</h2>
    <div class="column_offset">
        &nbsp;
    </div>
    <% slice_topics(certificate.topics).each do |topics_slice| %>
        <div class="column">
        <ul
        <% topics_slice.each do |topic| %>
                ><li><%= "#{topic.strip}" %></li
        <% end %>
        ></ul>
        </div>
    <% end %>
</div>

app/views/certificates/_event.html.erb
A IT Cursos certifica a participação de <strong><%= certifiable.name.upcase %></strong> no evento <strong><%= certificate.event.upcase %></strong>, com carga horária total de <strong><%= certificate.duration %></strong>,  realizado no período de <strong><%= certificate.start_date %></strong>, em Natal/RN<% if certificate.certifiable_type == "Lecturer" %>, na qualidade de <strong>PALESTRANTE</strong> com a seguinte palestra: <strong><%= certificate.lecture.upcase%></strong><% end %>.

app/views/certificates/_filter_form.html.erb
<h2>Filtrar Certificados</h2>

<%= form_tag(filter_certificates_url, :method => :get) do %>


  <% if flash[:error] %>
      <p id="error"><%= flash[:error] %></p>
  <% end %>


  <div class="field">
    <%= select(:certificate, :filter, Certificate.select("course_code").uniq.collect {|c| [c.course_code,c.course_code] }) %>
  </div>
  <div class="actions">
    <%= button_tag "Filter" %>
  </div>

  <% end %>

app/views/certificates/_filter_result.html.erb
<table>
  <tr>
    <th>Titulo</th>
    <th>Geração</th>
    <th>Enviado?</th>
    <th>Tentativas</th>
    <th>uuid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% certificates.each do |certificate| %>
  <tr>
    <td><%= link_to certificate.certifiable_name, certificate.certifiable %></td>
    <td><%= certificate.created_at.strftime("%d-%m-%Y") %></td>
    <td><%= certificate.sent %></td>
    <td><%= link_to certificate.attempts, certificate_send_attempts_path(certificate) %></td>
    <td><%= certificate.uuid %></td>
    <td><%= link_to 'Show', certificate %></td>
    <td><%= link_to 'Destroy', certificate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Enviar', email_certificate_path(certificate), method: :post%></td>
  </tr>
<% end %>
</table>

app/views/certificates/_form.html.erb
<%= form_for([certifiable,certificate]) do |f| %>
  <% if certificate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(certificate.errors.count, "error") %> prohibited this certificate from being saved:</h2>

      <ul>
      <% certificate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event %><br />
    <%= f.text_field :event %>
  </div>

  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>

  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.text_field :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.text_field :end_date %>
  </div>

  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>

  <div class="field">
    <%= f.label :course %><br />
    <%= f.text_field :course %>
  </div>

  <div class="field">
    <%= f.label :course_code %><br />
    <%= f.text_field :course_code %>
  </div>

  <div class="field">
    <%= f.label :topics %><br />
    <%= f.text_field :topics %>
  </div>


  <% if certifiable.class.name == "Lecturer" %>
  <div class="field">
    <%= f.label :lecture %><br />
    <%= f.text_field :lecture %>
  </div>
  <% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/certificates/_search_form.html.erb
<%= form_tag(search_certificates_url, :method => :get) do %>


  <% if flash[:error] %>
      <p id="error"><%= flash[:error] %></p>
  <% end %>


  <div class="field">
    <%= text_field :certificate, :search %>
  </div>
  <div class="actions">
    <%= button_tag "Search" %>
  </div>

<% end %>

app/views/certificates/index.html.erb
<h1>Validar Certificados</h1>

<%= render 'search_form' %>
<br /><br />
<%= render 'filter_form' %>

<% if @certificates %>
<%= render 'filter_result', :certificates => @certificates %>
<% end %>
<br />

app/views/certificates/new.html.erb
<h1>New certificate</h1>

<%= render 'form', :certifiable => @certifiable, :certificate => @certificate %>

<%= link_to 'Back', @student %>

app/views/certificates/news.html.erb
<h2>Validar Certificados</h2>

<%= form_tag(create_validation_url, :method => :post) do %>
  <% if flash[:error] %>
      <p id="error"><%= flash[:error] %></p>
  <% end %>

  <div class="field">
    <%= input_tag(:validation, :uuid %>
  </div>

  <% end %>

app/views/certificates/show.html.erb
<div id="wrap" class="hcenter">
    <div id="head">

    </div>
    <div id="content_head">
        <h1 class="hcenter">CERTIFICADO</h1>
    </div>

    <div id="content">
        <p class="hcenter">
<% if @certificate.kind == 'event' %>
    <%= render 'event', :certificate => @certificate, :certifiable => @certifiable %>
<% else %>
    <%= render 'course', :certificate => @certificate, :certifiable => @certifiable %>
<% end %>
        </p>
    </div>
    <div id="foot">
        <p class="vcenter">N. <%= @certificate.uuid.upcase %></p>
    </div>
</div>