config/routes.rb
require 'sidekiq/web'

Certificados::Application.routes.draw do

  resources :validations, :only => [:new, :create, :show]

  resources :certificates, :only => [] do
    get :autocomplete_certificate_uuid, :on => :collection
  end

  get "students/imports/new" => "students#new_import", :as => :new_students_import
  post "students/imports" => "students#create_import", :as => :students_import
  get "lecturers/imports/new" => "lecturers#new_import", :as => :new_lecturers_import
  post "lecturers/imports" => "lecturers#create_import", :as => :lecturers_import
  post "certificates/:certificate_id/mail/" => "certificate_mail#create", :as => :email_certificate
  get "certificates/search/" => "certificates#search", :as => :search_certificates
  get "certificates/" => "certificates#index", :as => :certificates
  get "certificates/filter" => "certificates#filter", :as => :filter_certificates


  [:lecturers, :students].each do |r|
    resources r do
      resources :certificates, :except => [:edit, :update, :index], :shallow => true do
        resources :send_attempts, :only => [:index], :shallow => true
      end
    end
  end

  resource :validation, :only => [:new, :create], :shallow => true

  mount Sidekiq::Web, at: "/sidekiq"
  root :to => "certificates#index"
end

app/models/lecturer.rb
class Lecturer < ActiveRecord::Base
  attr_accessible :email, :name, :phone, :resume, :certificate_attributes

  has_many :certificates, :as => :certifiable, :dependent => :destroy

end

app/controllers/lecturers_controller.rb
# encoding: utf-8

class LecturersController < ApplicationController
  def new_import
  end

  def create_import
    lecturers = params[:certifiable_attributes]
    lecturers.each do |lecturer|
      certificate = lecturer[:certificate_attributes]
      certificate[:kind] = "event"
      certificate[:course_code] = certificate[:event]
      lecturer.delete :certificate_attributes
      l = Lecturer.create(lecturer)
      l.certificates.create(certificate)
    end

    redirect_to lecturers_path
  end

  def index
    @lecturers = Lecturer.all
  end

  def show
    @lecturer = Lecturer.find(params[:id])
  end

  def new
    @lecturer = Lecturer.new
  end

  def edit
    @lecturer = Lecturer.find(params[:id])
  end

  def create
    @lecturer = Lecturer.new(params[:lecturer])

    if @lecturer.save
      redirect_to @lecturer, notice: 'Lecturer was successfully created.'
    else
      render :new
    end
  end

  def update
    @lecturer = Lecturer.find(params[:id])
    if @lecturer.update_attributes(params[:lecturer])
      redirect_to @lecturer, notice: 'Lecturer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @lecturer = Lecturer.find(params[:id])
    @lecturer.destroy
    redirect_to lecturers_url
  end
end

app/views/lecturers/_form.html.erb
<%= form_for(lecturer) do |f| %>
  <% if lecturer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lecturer.errors.count, "error") %> prohibited this lecturer from being saved:</h2>

      <ul>
      <% lecturer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lecturers/edit.html.erb
<h1>Editing lecturer</h1>

<%= render 'form', :lecturer => @lecturer %>

<%= link_to 'Show', @lecturer %> |
<%= link_to 'Back', lecturers_path %>

app/views/lecturers/index.html.erb
<h1>Listing lecturers</h1>
<%= link_to 'New Lecturer', new_lecturer_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lecturers.each do |lecturer| %>
  <tr>
    <td><%= lecturer.name %></td>
    <td><%= lecturer.email %></td>
    <td><%= lecturer.phone %></td>
    <td><%= link_to 'Show', lecturer %></td>
    <td><%= link_to 'Edit', edit_lecturer_path(lecturer) %></td>
    <td><%= link_to 'Destroy', lecturer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lecturer', new_lecturer_path %>

app/views/lecturers/new.html.erb
<h1>New lecturer</h1>

<%= render 'form', :lecturer => @lecturer %>

<%= link_to 'Back', lecturers_path %>

app/views/lecturers/new_import.html.erb
<h2>Cole aqui os dados do Excel</h1>
<div id="dataTable" class="dataTable"
data-attributes="name,email,phone,resume,event,duration,lecture"
data-end="3"></div>

<button class="submit">Enviar</button>
<br /><br />
<%= link_to 'Voltar', lecturers_path %>
<form action="<%= lecturers_import_path %>" id="import_data" method="POST">
</form>

app/views/lecturers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @lecturer.name %>
</p>

<p>
  <b>Email:</b>
  <%= @lecturer.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @lecturer.phone %>
</p>


<%= link_to 'Edit', edit_lecturer_path(@lecturer) %> |
<%= link_to 'Back', lecturers_path %> |
<%= link_to 'Novo Certificado', new_lecturer_certificate_path(@lecturer) %>

<h2>Certificados</h2>

<% if @lecturer.certificates.empty? %>
    <p>Não existem certificados gerados para este professor.</p>
<% else %>
<table>
  <tr>
    <th>Evento</th>
    <th>Geração</th>
    <th>Enviado?</th>
    <th>Tentativas</th>
    <th>uuid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lecturer.certificates.each do |certificate| %>
  <tr>
    <td><%= certificate.event %></td>
    <td><%= certificate.created_at.strftime("%d-%m-%Y %H:%M") %></td>
    <td><%= certificate.sent %></td>
    <td><%= link_to certificate.attempts, certificate_send_attempts_path(certificate) %></td>
    <td><%= certificate.uuid %></td>
    <td><%= link_to 'Show', certificate %></td>
    <td><%= link_to 'Destroy', certificate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Enviar', email_certificate_path(certificate), method: :post%></td>
  </tr>
<% end %>
</table>
<% end %>