config/routes.rb
require 'sidekiq/web'

Certificados::Application.routes.draw do

  resources :validations, :only => [:new, :create, :show]

  resources :certificates, :only => [] do
    get :autocomplete_certificate_uuid, :on => :collection
  end

  get "students/imports/new" => "students#new_import", :as => :new_students_import
  post "students/imports" => "students#create_import", :as => :students_import
  get "lecturers/imports/new" => "lecturers#new_import", :as => :new_lecturers_import
  post "lecturers/imports" => "lecturers#create_import", :as => :lecturers_import
  post "certificates/:certificate_id/mail/" => "certificate_mail#create", :as => :email_certificate
  get "certificates/search/" => "certificates#search", :as => :search_certificates
  get "certificates/" => "certificates#index", :as => :certificates
  get "certificates/filter" => "certificates#filter", :as => :filter_certificates


  [:lecturers, :students].each do |r|
    resources r do
      resources :certificates, :except => [:edit, :update, :index], :shallow => true do
        resources :send_attempts, :only => [:index], :shallow => true
      end
    end
  end

  resource :validation, :only => [:new, :create], :shallow => true

  mount Sidekiq::Web, at: "/sidekiq"
  root :to => "certificates#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Certificados</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>



  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="brand" href="./">Sendtificate</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li class="dropdown">
              <%= link_to "Estudantes", students_path, :class => "dropdown-toggle", :"data-toggle" => "dropdown" %>
              <ul class="dropdown-menu">
                <li class="">
                  <%= link_to "Todos", students_path %>
                </li>                                
                <li class="">
                  <%= link_to "Novo", new_student_path %>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <%= link_to "Professores", lecturers_path, :class => "dropdown-toggle", :"data-toggle" => "dropdown" %>
              <ul class="dropdown-menu">
                <li class="">
                  <%= link_to "Todos", lecturers_path %>
                </li>                                
                <li class="">
                  <%= link_to "Novo", new_lecturer_path %>
                </li>
              </ul>
            </li>
            <li class="">
              <%= link_to "Certificados", certificates_path %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>


  <%= yield %>
  <%= javascript_include_tag "application" %>
</body>
</html>